### ISSUE TITLE
Tool download progress not build-log friendly

### ISSUE THREAD

**Issue by kevinbosman** [fluffynuts/gulp-tasks#14]
**Not sure at this stage how this could be handled, so I'm just putting it out here mostly for comment:**

When gulp-tasks downloads tools, it very helpfully updates the interactive console with progress of the download.
However, when console output is diverted to a stream (eg. when used on a build server), you get something like the following, which is a lot of unhelpful noise for a build log:

```
Start download of "http://dist.nuget.org/win-x86-commandline/latest/nuget.exe"

               
0% of 4.78mb
               
1% of 4.78mb
               
2% of 4.78mb
               
3% of 4.78mb
               
4% of 4.78mb
               
5% of 4.78mb
               
```
... all the way to ...
```
98% of 4.78mb
               
99% of 4.78mb
               
100% of 4.78mb
               

               
-> download complete!
```
(notice also the extra whitespace in there if you do a "select all" here)

**Comment by fluffynuts** [comment]
addressed in https://github.com/fluffynuts/gulp-tasks/commit/452a5f1f19a5b608cb25c037963f2fcd0e96bdf0 - automated tooling can be run with the SUPPRESS_DOWNLOAD_PROGRESS environment variable set to (surprisingly) suppress the download progress (:

**Comment by fluffynuts** [comment]
(I've also applied this env var on Jenkins, globally, and restarted the build service. Logs should be better now)
